import Head from "next/head";
import { useState } from "react";
import { Button } from "react-daisyui";
import { useRouter } from "next/router";

import FilterThoughts from "../components/FilterThoughts";

export default function Home() {
  const [filterValue, setFilterValue] = useState("");
  const router = useRouter();

  const handleOnSubmitThought = () => {
    router.push("/submit");
  };

  const handleOnFilter = (value: string) => {
    if (filterValue === value) return;

    setFilterValue(value);
    alert(value);
  };

  return (
    <section>
      <Head>
        <title>Thoughts Board</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="flex justify-end mr-3">
        <Button
          color="primary"
          className="btn-md"
          onClick={handleOnSubmitThought}
        >
          Submit a Thought
        </Button>
        <FilterThoughts onFilter={handleOnFilter} />
      </section>
    </section>
  );
}
