import Head from "next/head";

export default function Home() {
  return (
    <main>
      <Head>
        <title>Thoughts Board</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="italic">HEY</h1>
    </main>
  );
}
